# Generated by Django 4.1.7 on 2023-03-23 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_name', models.TextField()),
                ('replacement_list', models.TextField(blank=True, null=True)),
                ('element_classification', models.TextField()),
            ],
        ),
    ]
